version: '2'
services:
  frontend:
    build:
      context: .
    environment:
      - API_BASEURL='https://db907f3a697198fae10dc93ba55e3d75.balena-devices.com:8080'
    ports:
      - "4200:4200"
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - frontend-data:/var/www/html
    restart: always
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.procfs: '1'
volumes:
  frontend-data: {}








